"""empty message

Revision ID: 58c33ab276b1
Revises: 53f8b1863436
Create Date: 2024-09-30 16:43:14.345736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c33ab276b1'
down_revision = '53f8b1863436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job', sa.Text(), nullable=True))
        batch_op.drop_column('jon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jon', sa.TEXT(), nullable=True))
        batch_op.drop_column('job')

    # ### end Alembic commands ###
